### PR TITLE
Add common stale action

### PR DESCRIPTION
**Pull request by thozza**
Also update README.

### CODE REVIEW

**Review by achilleas-k — COMMENTED** [review]
Good idea.  I like this.  I'm curious how the reset works when the label is removed or a comment is made.  Does the 30 day countdown begin again?

**Comment by ondrejbudai** [comment]
I think the workflow needs a schedule. Otherwise, this this perfect.

**Comment by ondrejbudai** [comment]
Oh, this is just a composite action, it needs to be enabled per repo, I see.

Cannot we just have central copy of this workflow, so we don't need to add it to every repo?

**Comment by thozza** [comment]
> Oh, this is just a composite action, it needs to be enabled per repo, I see.

The intention of this repo is to have the action configured in a single place and then enable it in each repo where we want it... I'm open to suggestions if you know of a better way.

> Cannot we just have central copy of this workflow, so we don't need to add it to every repo?

From what I checked, the only option to have it in every repo where we want to use it. There is no such thing as organization-wide actions, or something similar.

I can probably create a scheduled workflow in this repo, which could be then copied over to other repos, but that's about it. I'm also not sure if we want to use Schutzbot's GH token or let GitHub create new action-specific token on each run. since the action calls GH API where rate limiting applies. So using a single bot token could probably make us hit the rate limit more easily... :thinking:

**Comment by thozza** [comment]
> Good idea. I like this. I'm curious how the reset works when the label is removed or a comment is made. Does the 30 day countdown begin again?

Yes, it should be as you described... More information is available at https://github.com/actions/stale

**Comment by ondrejbudai** [comment]
FTR, having the action handle other repositories is not yet possible, see: https://github.com/actions/stale/pull/1081

**Review by ondrejbudai — APPROVED** [review]
Awesome, thanks for proposing this!

**Review by achilleas-k — APPROVED** [review]

**Pull request merged**
